---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: snmpd-monitor
  name: snmpd-monitor
spec:
  selector:
    matchLabels:
      app: snmpd-monitor
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: snmpd-monitor
    spec:
      hostNetwork: true
      # Enable the pod to access the host's /proc filesystem
      hostPID: true
      containers:
      - image: net_snmp_image:latest
        imagePullPolicy: Never
        name: snmpd-monitor
        volumeMounts:
        - mountPath: /etc/snmp/snmpd.conf
          name: volume-snmpd-monitor
        - mountPath: /host-root
          name: host-root-partition
        ports: 
        - containerPort: 161
          protocol: UDP
          hostPort: 161
        resources: {}
      volumes:
      - name: volume-snmpd-monitor
        hostPath:
        # directory location on host
          path: /cvpi/cvp-snmp-container-main/snmpd.conf
          type: FileOrCreate
      - name: host-root-partition
        hostPath:
        # directory location on host
          path: /
          type: Directory
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
