---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: snmpd-monitor
  name: snmpd-monitor
spec:
  ports:
  - name: snmp-monitoring-port
    # If required, modify here the port opened on the host side. The range of valid ports is 9000-32000.
    nodePort: 30161
    port: 161
    protocol: UDP
    targetPort: 161
  selector:
    app: snmpd-monitor
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: snmpd-monitor
  name: snmpd-monitor
spec:
  selector:
    matchLabels:
      app: snmpd-monitor
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: snmpd-monitor
    spec:
      containers:
      - image: net_snmp_image:latest
        imagePullPolicy: Never
        name: snmpd-monitor
        volumeMounts:
        - mountPath: /etc/snmp/snmpd.conf
          name: volume-snmpd-monitor
        - mountPath: /host-root
          name: host-root-partition
        ports: 
        - containerPort: 161
        resources: {}
      volumes:
      - name: volume-snmpd-monitor
        hostPath:
        # directory location on host
          path: /cvpi/snmpd.conf
          type: FileOrCreate
      - name: host-root-partition
        hostPath:
        # directory location on host
          path: /
          type: Directory
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
