apiVersion: v1
clusters:
- cluster:
    certificate-authority: /host-root/cvpi/tls/certs/kube-cert.pem
    server: https://127.0.0.1:6443
  name: local
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
kind: Config
preferences: {}
users:
- name: kubelet
  user:
    client-certificate: /host-root/cvpi/tls/certs/kube-cert.pem
    client-key: /host-root/cvpi/tls/certs/kube-cert.pem
